apiVersion: v1
kind: Pod
metadata:
  name: api-v1
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
  labels:
    app: api
    version: v1
spec:
  containers:
  - name: web
    image: docker.io/vikramkhatri/gorest:1.0
    ports:
    - containerPort: 8080
      name: http
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: api-v2
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
  labels:
    app: api
    version: v2
spec:
  containers:
  - name: web
    image: docker.io/vikramkhatri/gorest:1.0
    ports:
    - containerPort: 8080
      name: http
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: api
    version: v1
---
