apiVersion: v1
kind: Pod
metadata:
  name: web
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
  labels:
    app: web
spec:
  containers:
  - name: web
    image: docker.io/vikramkhatri/hello-echo:1.0
    ports:
    - containerPort: 8080
      name: http
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: UPSTREAM_SERVICE
      value: "http://api-service.consul.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
spec:
  ports:
  - name: http
    port: 8080
    nodePort: 30145
  selector:
    app: web
  type: NodePort
---
